[build-system]
requires = ["setuptools>=42", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "statica"
version = "1.0.0"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]